# 运行模式(debug:调试,test:测试,release:正式)
run-mode: "debug"
# swagger
swagger: true
# 静态站点目录(也可以启动服务时使用-www指定)
www: "web"
# 启动时是否打印配置参数
print-config: true

# zap logger configuration
Log:
  # 日志级别(1:fatal 2:error,3:warn,4:info,5:debug,6:trace)
  level: 5
  # 日志格式（支持输出格式：text/json）
  format: 'text'
  # 日志输出(支持：stdout/stderr/file)
  output: "stdout"
  # 指定日志输出的文件路径
  output-file: "data/gin-ng-admin.log"
  # 是否启用日志钩子
  enable-hook: false
  # 写入钩子的日志级别
  hook-levels: [ "info","warn","error" ]
  # 日志钩子(支持：gorm/mongo)
  kook: "gorm"
  # 写入钩子的最大工作线程数量
  hook-max-thread: 1
  # 写入钩子的最大缓冲区数量
  hook-max-buffer: 512


# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80

# mysql connect configuration

mysql:
  path: ''
  config: ''
  db-name: ''
  username: ''
  password: ''
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
